<?php

namespace ContainerKyipIQF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PHwQa0_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pHwQa0.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pHwQa0.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'initialisationUserDataService' => ['privates', 'App\\Service\\InitialisationUserDataService', 'getInitialisationUserDataServiceService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'initialisationUserDataService' => 'App\\Service\\InitialisationUserDataService',
            'translator' => '?',
        ]);
    }
}
