<?php

namespace ContainerKyipIQF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LO5TKjjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lO5TKjj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lO5TKjj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'image' => ['privates', '.errored..service_locator.lO5TKjj.App\\Entity\\Images', NULL, 'Cannot autowire service ".service_locator.lO5TKjj": it references class "App\\Entity\\Images" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'image' => 'App\\Entity\\Images',
            'manager' => '?',
        ]);
    }
}
