<?php

namespace ContainerKyipIQF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FhAR7n9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FhAR7n9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FhAR7n9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'driver' => ['privates', '.errored..service_locator.FhAR7n9.App\\Entity\\Driver', NULL, 'Cannot autowire service ".service_locator.FhAR7n9": it references class "App\\Entity\\Driver" but no such service exists.'],
            'driverRepository' => ['privates', 'App\\Repository\\DriverRepository', 'getDriverRepositoryService', true],
        ], [
            'driver' => 'App\\Entity\\Driver',
            'driverRepository' => 'App\\Repository\\DriverRepository',
        ]);
    }
}
