<?php

namespace ContainerKyipIQF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGaleryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Hx0mXiz.App\Entity\Galery' shared service.
     *
     * @return \App\Entity\Galery
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Hx0mXiz": it references class "App\\Entity\\Galery" but no such service exists.');
    }
}
