<?php

namespace ContainerKyipIQF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImages2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lO5TKjj.App\Entity\Images' shared service.
     *
     * @return \App\Entity\Images
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lO5TKjj": it references class "App\\Entity\\Images" but no such service exists.');
    }
}
