<?php

namespace Container1rxAUTI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9qcxw_NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9qcxw.N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9qcxw.N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'driverRepository' => ['privates', 'App\\Repository\\DriverRepository', 'getDriverRepositoryService', true],
            'image' => ['privates', '.errored..service_locator.9qcxw.N.App\\Entity\\Images', NULL, 'Cannot autowire service ".service_locator.9qcxw.N": it references class "App\\Entity\\Images" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'driverRepository' => 'App\\Repository\\DriverRepository',
            'image' => 'App\\Entity\\Images',
            'manager' => '?',
        ]);
    }
}
