<?php

namespace Container1rxAUTI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YlxcikIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YlxcikI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YlxcikI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'driver' => ['privates', '.errored..service_locator.YlxcikI.App\\Entity\\Driver', NULL, 'Cannot autowire service ".service_locator.YlxcikI": it references class "App\\Entity\\Driver" but no such service exists.'],
            'galeryRepository' => ['privates', 'App\\Repository\\GaleryRepository', 'getGaleryRepositoryService', true],
        ], [
            'driver' => 'App\\Entity\\Driver',
            'galeryRepository' => 'App\\Repository\\GaleryRepository',
        ]);
    }
}
