<?php

namespace Container1rxAUTI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDriver2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FhAR7n9.App\Entity\Driver' shared service.
     *
     * @return \App\Entity\Driver
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FhAR7n9": it references class "App\\Entity\\Driver" but no such service exists.');
    }
}
