<?php

namespace Container1rxAUTI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGaleryTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\GaleryType' shared autowired service.
     *
     * @return \App\Form\GaleryType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/GaleryType.php';

        return $container->privates['App\\Form\\GaleryType'] = new \App\Form\GaleryType();
    }
}
