<?php

namespace Container1rxAUTI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitialisationUserDataServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\InitialisationUserDataService' shared autowired service.
     *
     * @return \App\Service\InitialisationUserDataService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/InitialisationUserDataService.php';

        return $container->privates['App\\Service\\InitialisationUserDataService'] = new \App\Service\InitialisationUserDataService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
